#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-zeta =							\
	papers/zeta/packages.tex					\
	papers/zeta/main.tex						\
	papers/zeta/references.bib					\
	papers/zeta/teil0_einleitung.tex				\
	papers/zeta/teil1_konvergenz_divergenz.tex			\
	papers/zeta/teil2_zeta.tex					\
	papers/zeta/teil3_analytische_fortsetzung.tex			\
	papers/zeta/teil4_fazit.tex

