#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-geradlinig =						\
	papers/geradlinig/packages.tex					\
	papers/geradlinig/main.tex					\
	papers/geradlinig/references.bib				\
	papers/geradlinig/teil0.tex					\
	papers/geradlinig/teil1.tex					\
	papers/geradlinig/teil2.tex					\
	papers/geradlinig/teil3.tex

