#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-julia =							\
	papers/julia/packages.tex					\
	papers/julia/main.tex						\
	papers/julia/references.bib					\
	papers/julia/chapters/1_definition_julia.tex			\
	papers/julia/chapters/2_definition_mandelbrot.tex		\
	papers/julia/chapters/3_zweck.tex				\
	papers/julia/chapters/4_relation.tex				\
	papers/julia/chapters/5_visualisierung.tex

