#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
AUFGABENFILES +=							\
	chapters/020-holomorph/uebungsaufgaben/201.tex			\
	chapters/020-holomorph/uebungsaufgaben/202.tex			\
	chapters/020-holomorph/uebungsaufgaben/203.tex			\
	chapters/020-holomorph/uebungsaufgaben/204.tex			\
	chapters/020-holomorph/uebungsaufgaben/205.tex

CHAPTERFILES += 							\
	chapters/020-holomorph/1-holomorph.tex				\
	chapters/020-holomorph/11-diffbar.tex				\
	chapters/020-holomorph/12-cr.tex				\
	chapters/020-holomorph/13-polynome.tex				\
	chapters/020-holomorph/14-potenzreihen.tex			\
	chapters/020-holomorph/2-geometrie.tex				\
	chapters/020-holomorph/21-konform.tex				\
	chapters/020-holomorph/22-riemann.tex				\
	chapters/020-holomorph/23-anwendungen.tex			\
	chapters/020-holomorph/3-nichtholomorph.tex			\
	chapters/020-holomorph/31-zbarz.tex				\
	chapters/020-holomorph/32-komplexj.tex				\
	chapters/020-holomorph/fig/fig-imaginaerteil.tex		\
	chapters/020-holomorph/fig/fig-konform.tex			\
	chapters/020-holomorph/fig/fig-mittelwert.tex			\
	chapters/020-holomorph/fig/fig-polynome.tex			\
	chapters/020-holomorph/fig/fig-rekursion.tex			\
	chapters/020-holomorph/chapter.tex

