#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-hankel =						\
	papers/hankel/packages.tex					\
	papers/hankel/main.tex					\
	papers/hankel/references.bib				\
	papers/hankel/teil0.tex					\
	papers/hankel/teil1.tex					\
	papers/hankel/teil2.tex					\
	papers/hankel/teil3.tex

