#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
AUFGABENFILES +=							\
	chapters/050-differentialgleichungen/uebungsaufgaben/501.tex	\
	chapters/050-differentialgleichungen/uebungsaufgaben/502.tex	\
	chapters/050-differentialgleichungen/uebungsaufgaben/503.tex

CHAPTERFILES += 							\
	chapters/050-differentialgleichungen/1-potenzreihen.tex		\
	chapters/050-differentialgleichungen/11-exponentialfunktion.tex	\
	chapters/050-differentialgleichungen/12-schwingungen.tex	\
	chapters/050-differentialgleichungen/13-wurzel.tex		\
	chapters/050-differentialgleichungen/2-verallgemeinert.tex	\
	chapters/050-differentialgleichungen/3-fuchs.tex		\
	chapters/050-differentialgleichungen/31-warum.tex		\
	chapters/050-differentialgleichungen/32-fuchs.tex		\
	chapters/050-differentialgleichungen/fig/fig-wurzel.tex		\
	chapters/050-differentialgleichungen/fig/tab-wurzel.tex		\
	chapters/050-differentialgleichungen/chapter.tex

