%
% argument.m
%
% (c) 2026 Prof Dr Andreas Müller
%
global z;
z = [ 1, -0.5+0.5i, -0.2-0.7i ];
global p;
p = [ 0.85i, 1.3-1.5i ];
global r;
r = 1.3;

function retval = f(x, nz, np)
	global z;
	global p;
	zaehler = 1;
	i = 1;
	while (i <= nz)
		zaehler = zaehler * (x - z(i));
		i = i + 1;
	end
	nenner = 1;
	i = 1;
	while (i <= np)
		nenner = nenner * (x - p(i));
		i = i + 1;
	end
	retval = zaehler / nenner;
end

function retval = kurve(t, nz, np)
	global r;
	retval = f(r * exp(2i * pi * t), nz, np);
end

fn = fopen("argumentpfad.tex", "w");
fprintf(fn, "%%\n");
fprintf(fn, "%% argumentpfad.tex -- generated by argument.m, don't edit\n");
fprintf(fn, "%%\n");
fprintf(fn, "%% (c) 2026 Prof Dr Andreas Müller\n");
fprintf(fn, "%%\n");

function retval = punkt(x)
	retval = sprintf("(%.4f,%.4f)", real(x), imag(x));
end

fprintf(fn, "\\def\\nullstelleeins{%s}\n", punkt(z(1)));
fprintf(fn, "\\def\\nullstellezwei{%s}\n", punkt(z(2)));
fprintf(fn, "\\def\\nullstelledrei{%s}\n", punkt(z(3)));
fprintf(fn, "\\def\\poleins{%s}\n", punkt(p(1)));
fprintf(fn, "\\def\\polzwei{%s}\n", punkt(p(2)));
fprintf(fn, "\\def\\r{%.4f}\n", r);

function bildkurve(fn, name, nz, np)
	betrag = 0;
	fprintf(fn, "\\def\\bildkurve%s{\n", name);
	N = 1000;
	t = linspace(0, 2*pi, N);
	p = kurve(t(1), nz, np);
	betrag = abs(p);
	fprintf(fn, "\t%s", punkt(p));
	for i = (2:N)
		p = kurve(t(i), nz, np);
		if (betrag < abs(p))
			betrag = abs(p);
		end
		fprintf(fn, "\n\t-- %s", punkt(p));
	end
	fprintf(fn, "\n}\n");
	fprintf(fn, "\\def\\scale%s{%.4f}\n", name, 1.5 / betrag);
end

bildkurve(fn, "A", 1, 0);
bildkurve(fn, "B", 2, 0);
bildkurve(fn, "C", 3, 0);
bildkurve(fn, "D", 3, 1);
bildkurve(fn, "E", 3, 2);

fclose(fn);
