#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter3 =								\
	../slides/3/dreiseit.tex					\
	../slides/3/residuum.tex					\
	../slides/3/beliebig.tex					\
	../slides/3/konsequenzen.tex					\
	../slides/3/ring.tex
