#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-elliptisch =						\
	papers/elliptisch/packages.tex					\
	papers/elliptisch/main.tex					\
	papers/elliptisch/references.bib				\
	papers/elliptisch/teil0.tex					\
	papers/elliptisch/teil1.tex					\
	papers/elliptisch/teil2.tex					\
	papers/elliptisch/teil3.tex

