#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-buchberger =						\
	papers/buchberger/packages.tex					\
	papers/buchberger/main.tex					\
	papers/buchberger/references.bib				\
	papers/buchberger/einleitung.tex					\
	papers/buchberger/buchberger.tex					\
	papers/buchberger/sudoku.tex		\
	papers/buchberger/komplexitaet.tex
			

