#
# Makefile -- standalone images
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	argument.pdf							\
	bisektion.pdf							\
	hybrid.pdf							\
	quadtree.pdf

argument.pdf:	argument.tex
	pdflatex argument.tex

bisektion.pdf:	bisektion.tex
	pdflatex bisektion.tex

hybrid.pdf:	hybrid.tex
	pdflatex hybrid.tex

quadtree.pdf:	quadtree.tex
	pdflatex quadtree.tex

