%
% gitter.m
%
% (c) 2026 Prof Dr Andreas Müller
%
rand("seed", 4711);

Nx = 30;
Ny = 20;

w = 12;
h = 8;

x = cumsum(ones(1,Nx) + 2 * rand(1,Nx))
x = x - x(1);
x = (w / x(Nx)) * x;
y = cumsum(ones(1,Ny) + 2 * rand(1,Ny));
y = y - y(1);
y = (h / y(Ny)) * y;

fn = fopen("gitter.tex", "w");

%
% Header
%
fprintf(fn, "%%\n");
fprintf(fn, "%% gitter.tex -- generated by gitter.m, don't edit\n");
fprintf(fn, "%%\n");
fprintf(fn, "%% (c) 2026 Prof Dr Andreas Müller\n");
fprintf(fn, "%%\n");

%
% \gitter Makro
%
fprintf(fn, "\\def\\gitter{\n");

fprintf(fn, "\t\\foreach \\x in {\n");
fprintf(fn, "%.4f", x(1));
for i = (2:Nx)
	fprintf(fn, ",%.4f", x(i));
end
fprintf(fn, "}{\n");
fprintf(fn, "\t\t\\draw[line width=0.2pt] (\\x,-0.1) -- ++(0,%.4f);\n", h+0.2);
fprintf(fn, "\t}\n");

fprintf(fn, "\t\\foreach \\y in {\n");
fprintf(fn, "%.4f", y(1));
for i = (2:Ny)
	fprintf(fn, ",%.4f", y(i));
end
fprintf(fn, "}{\n");
fprintf(fn, "\t\t\\draw[line width=0.2pt] (-0.1,\\y) -- ++(%.4f,0);\n", w+0.2);
fprintf(fn, "\t}\n");

fprintf(fn, "}\n");

%
% Menge U
%
fprintf(fn, "\\def\\U{\n");
fprintf(fn, "\t\\fill[rounded corners=0.5cm,color=gray!20]\n");
fprintf(fn, "\t\t(0.2,0.2) rectangle (11.9,7.9);\n");
fprintf(fn, "\t\\fill[color=white,rotate=30] (7,0) ellipse(1.5cm and 1cm);\n");
fprintf(fn, "\t\\fill[color=white,rotate=-12] (1,6.7) ellipse(1.1cm and 0.8cm);\n");
fprintf(fn, "\t\\node at (%.4f,%.4f) {$U$};\n", w-0.5, h-0.5);
fprintf(fn, "}\n");

%
% Kette
%
fprintf(fn, "\\def\\kette{\n");
farbe = "kurveA";
p = [
	6,6;
	7,6;
	7,5;
	8,5;
	8,4;
	12,4;
	12,3;
	18,3;
	18,5;
	19,5;
	19,6;
	20,6;
	20,9;
	19,9;
	19,12;
	18,12;
	18,13;
	17,13;
	17,14;
	15,14;
	15,13;
	14,13;
	14,14;
	13,14;
	13,16;
	12,16;
	11,16;
	11,17;
	10,17;
	10,18;
	9,18;
	9,14;
	8,14;
	8,13;
	7,13;
	7,12;
	6,12;
	6,11;
	5,11;
	5,10;
	5,9;
	6,9;
];
n = size(p)(1);
fprintf(fn, "\\draw[color=%s,line width=1.2pt] (%.4f,%.4f)\n", farbe,
	x(p(1,1)), y(p(1,2)));
for i = (2:n)
	fprintf(fn, "\t-- (%.4f,%.4f)\n", x(p(i,1)), y(p(i,2)));
end
fprintf(fn, "\t-- cycle;\n");
X = x(10); Y = y(4);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(15); Y = y(3);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(16); Y = y(14);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(20); Y = y(8);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);
X = x(19); Y = y(11);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);
X = x(9); Y = y(16);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(5); Y = y(10);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(6); Y = y(7);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);

%
% zweiter Pfad
%
farbe = "kurveB";
p = [
	19,3;
	21,3;
	21,4;
	22,4;
	22,5;
	23,5;
	23,6;
	24,6;
	24,7;
	25,7;
	25,10;
	26,10;
	26,13;
	24,13;
	24,14;
	22,14;
	22,15;
	20,15;
	20,16;
	18,16;
	18,17;
	16,17;
	16,16;
	14,16;
	14,15;
	12,15;
	12,14;
	11,14;
	11,12;
	10,12;
	10,11;
	9,11;
	9,8;
	10,8;
	10,7;
	11,7;
	11,6;
	14,6;
	14,7;
	15,7;
	15,6;
	16,6;
	16,5;
	17,5;
	17,4;
	19,4;
];
n = size(p)(1);
fprintf(fn, "\\draw[color=%s,line width=1.2pt] (%.4f,%.4f)\n", farbe,
	x(p(1,1)), y(p(1,2)));
for i = (2:n)
	fprintf(fn, "\t-- (%.4f,%.4f)\n", x(p(i,1)), y(p(i,2)));
end
fprintf(fn, "\t-- cycle;\n");
X = x(20); Y = y(3);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(13); Y = y(6);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(15); Y = y(16);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(17); Y = y(17);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(19); Y = y(16);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(21); Y = y(15);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(23); Y = y(14);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(25); Y = y(13);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);

X = x(26); Y = y(11);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(25); Y = y(9);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(9); Y = y(10);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);
X = x(11); Y = y(13);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);

%
% Kurve 3
%
farbe = "kurveC";
p = [
	24,15;
	25,15;
	25,14;
	26,14;
	26,15;
	27,15;
	27,18;
	25,18;
	25,19;
	16,19;
	16,18;
	19,18;
	19,17;
	22,17;
	22,16;
	24,16;
]
n = size(p)(1);
fprintf(fn, "\\draw[color=%s,line width=1.2pt] (%.4f,%.4f)\n", farbe,
	x(p(1,1)), y(p(1,2)));
for i = (2:n)
	fprintf(fn, "\t-- (%.4f,%.4f)\n", x(p(i,1)), y(p(i,2)));
end
fprintf(fn, "\t-- cycle;\n");
X = x(27); Y = y(17);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);
X = x(26); Y = y(18);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(21); Y = y(19);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(18); Y = y(18);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(21); Y = y(17);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(23); Y = y(16);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);

farbe = "kurveD";
p = [
	3,19;
	5,19;
	5,18;
	4,18;
	4,14;
	6,14;
	6,13;
	5,13;
	5,12;
	4,12;
	4,8;
	5,8;
	5,6;
	6,6;
	6,4;
	8,4;
	8,3;
	7,3;
	7,2;
	4,2;
	4,3;
	3,3;
	3,4;
	2,4;
	2,11;
	3,11;
]
n = size(p)(1);
fprintf(fn, "\\draw[color=%s,line width=1.2pt] (%.4f,%.4f)\n", farbe,
	x(p(1,1)), y(p(1,2)));
for i = (2:n)
	fprintf(fn, "\t-- (%.4f,%.4f)\n", x(p(i,1)), y(p(i,2)));
end
fprintf(fn, "\t-- cycle;\n");
X = x(4); Y = y(19);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(5); Y = y(14);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(7); Y = y(4);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(6); Y = y(2);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(4); Y = y(16);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(4); Y = y(10);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(5); Y = y(7);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(6); Y = y(5);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(2); Y = y(9);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);
X = x(3); Y = y(15);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);

farbe = "kurveE";
p = [
	22,2;
	28,2;
	28,4;
	29,4;
	29,6;
	28,6;
	28,8;
	22,8;
]
n = size(p)(1);
fprintf(fn, "\\draw[color=%s,line width=1.2pt] (%.4f,%.4f)\n", farbe,
	x(p(1,1)), y(p(1,2)));
for i = (2:n)
	fprintf(fn, "\t-- (%.4f,%.4f)\n", x(p(i,1)), y(p(i,2)));
end
fprintf(fn, "\t-- cycle;\n");
X = x(25); Y = y(2);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(-0.1,0);\n", X, Y);
X = x(24); Y = y(8);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(27); Y = y(8);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0.1,0);\n", X, Y);
X = x(29); Y = y(5);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(28); Y = y(3);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,-0.1);\n", X, Y);
X = x(22); Y = y(3);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);
X = x(22); Y = y(7);
fprintf(fn, "\t\\draw[->,color=%s,line width=1.2pt]\n", farbe);
fprintf(fn, "\t\t(%.4f,%4f) -- ++(0,0.1);\n", X, Y);

fprintf(fn, "}\n");

%
% Macro \selektiert
%
fprintf(fn, "\\def\\selektiert{\n");
p = [
	 5,  9, 10;
	 6,  6, 11;
	 7,  5, 12;
	 8,  4, 13;
	 9,  4,  7;
	 9, 11, 17;
	10,  4,  6;
	10, 12, 16;
	11,  4,  5;
	11, 14, 15;
	12,  3,  5;
	12, 15, 15;
	13,  3,  5;
	14,  3,  6;
	15,  3,  5;
	16,  3,  4;
	16, 18, 18;
	17,  3,  3;
	17, 18, 18;
	18,  4,  4;
	18, 18, 18;
	19,  3,  5;
	19, 17, 18;
	20, 17, 18;
	21, 17, 18;
	22, 16, 18;
	23, 16, 18;
	24, 15, 18;
	25, 14, 17;
	26, 15, 17;
];
n = size(p)(1);
for i = (1:n)
	fprintf(fn, "\t\\fill[color=selektiertplus!20] ");
	fprintf(fn, "(%.4f,%.4f) rectangle (%.4f,%.4f);\n",
		x(p(i,1)), y(p(i,2)), x(p(i,1)+1), y(p(i,3)+1));
end

fprintf(fn, "\\node[color=selektiertplus] at (3.0,3.4) {$+1$};\n");
fprintf(fn, "\\node[color=selektiertplus] at (9.7,7.0) {$+1$};\n");

p = [
	 2,  4, 10;
	 3,  3, 18;
	 4,  2,  7;
	 4, 12, 13;
	 4, 18, 18;
	 5,  2,  5;
	 5, 13, 13;
	 6,  2,  3;
	 7,  3,  3;
	13, 14, 14;
	14, 13, 15;
	15, 14, 15;
	16, 14, 16;
	17, 13, 16;
	18,  4,  4;
	18, 12, 15;
	19,  3,  5;
	19,  9, 15;
	20,  3, 14;
	21,  4, 14;
	22,  2,  4;
	22,  8, 13;
	23,  8, 13;
	23,  2,  5;
	24,  8, 12;
	24,  2,  6;
	25, 10, 12;
	25,  2,  7;
	26,  2,  7;
	27,  2,  7;
	28,  4,  5;
];
n = size(p)(1);
for i = (1:n)
	fprintf(fn, "\t\\fill[color=selektiertminus!20] ");
	fprintf(fn, "(%.4f,%.4f) rectangle (%.4f,%.4f);\n",
		x(p(i,1)), y(p(i,2)), x(p(i,1)+1), y(p(i,3)+1));
end

p = [
	22,  5,  7;
	23,  6,  7;
	24,  7,  7;
];
n = size(p)(1);
for i = (1:n)
	fprintf(fn, "\t\\fill[color=selektiertminus!40] ");
	fprintf(fn, "(%.4f,%.4f) rectangle (%.4f,%.4f);\n",
		x(p(i,1)), y(p(i,2)), x(p(i,1)+1), y(p(i,3)+1));
end

fprintf(fn, "\\node[color=selektiertminus] at (1.5,1.2) {$-1$};\n");
fprintf(fn, "\\node[color=selektiertminus] at (10.5,1.3) {$-1$};\n");
fprintf(fn, "\\node[color=selektiertminus] at (9.4,4.3) {$-1$};\n");
fprintf(fn, "\\node[color=selektiertminus] at (9.7,2.3) {$-2$};\n");

fprintf(fn, "}\n");

fclose(fn);
