#
# Makefile -- create images for chapter 4
#
# (c) 2026 Prof Dr Andreas Müller
#
all:									\
	argument.pdf							\
	beliebig.pdf							\
	cauchyverteilung.pdf						\
	deformation.pdf							\
	dreiecke.pdf							\
	ecos.pdf							\
	green.pdf							\
	hauptwert.pdf							\
	homotopie.pdf							\
	kettenzyklen.pdf						\
	lochgebiet.pdf							\
	merohomolog.pdf							\
	methode.pdf							\
	nachbar.pdf							\
	paar.pdf							\
	raender.pdf							\
	rechteck.pdf							\
	residuum.pdf							\
	treppe.pdf							\
	wege.pdf							\
	sinxx.pdf							\
	gitterapprox.pdf

wege.pdf:	wege.tex
	pdflatex wege.tex

rechteck.pdf:	rechteck.tex
	pdflatex rechteck.tex

residuum.pdf:	residuum.tex
	pdflatex residuum.tex

argument.pdf:	argument.tex
	pdflatex argument.tex

lochgebiet.pdf:	lochgebiet.tex
	pdflatex lochgebiet.tex

homotopie.pdf:	homotopie.tex
	pdflatex homotopie.tex

dreiecke.pdf:	dreiecke.tex
	pdflatex dreiecke.tex

beliebig.pdf:	beliebig.tex
	pdflatex beliebig.tex

green.pdf:	green.tex
	pdflatex green.tex

deformation.pdf:	deformation.tex
	pdflatex deformation.tex

cauchyverteilung.pdf:	cauchyverteilung.tex
	pdflatex cauchyverteilung.tex

ecos.pdf:	ecos.tex
	pdflatex ecos.tex

paar.pdf:	paar.tex
	pdflatex paar.tex

merohomolog.pdf:	merohomolog.tex
	pdflatex merohomolog.tex

kettenzyklen.pdf:	kettenzyklen.tex
	pdflatex kettenzyklen.tex

raender.pdf:	raender.tex
	pdflatex raender.tex

hauptwert.pdf:	hauptwert.tex
	pdflatex hauptwert.tex

methode.pdf:	methode.tex
	pdflatex methode.tex

sinxx.pdf:	sinxx.tex sinxxdata.tex
	pdflatex sinxx.tex

sinxxdata.tex:	sinxx.m
	octave sinxx.m

gitterapprox.pdf:	gitterapprox.tex gitter.tex
	pdflatex gitterapprox.tex

gitter.tex:	gitter.m
	octave gitter.m

treppe.pdf:	treppe.tex
	pdflatex treppe.tex

nachbar.pdf:	nachbar.tex
	pdflatex nachbar.tex
