#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	rechtwinklig.pdf						\
	hoehe.pdf							\
	katheten.pdf							\
	sinxx.pdf							\
	ausgangskreis.pdf						\
	k1.pdf								\
	k2.pdf								\
	k3.pdf								\
	zahlengerade.pdf						\
	rechteck.pdf							\
	fourier.pdf							\
	pi2.pdf

rechtwinklig.pdf:	rechtwinklig.tex
	pdflatex rechtwinklig.tex

hoehe.pdf:	hoehe.tex
	pdflatex hoehe.tex

katheten.pdf:	katheten.tex
	pdflatex katheten.tex

sinxx.pdf:	sinxx.tex
	pdflatex sinxx.tex

ausgangskreis.pdf:	ausgangskreis.tex
	pdflatex ausgangskreis.tex

k1.pdf:	k1.tex
	pdflatex k1.tex

k2.pdf:	k2.tex
	pdflatex k2.tex

k3.pdf:	k3.tex
	pdflatex k3.tex

zahlengerade.pdf:	zahlengerade.tex
	pdflatex zahlengerade.tex

rechteck.pdf:	rechteck.tex
	pdflatex rechteck.tex

fourier.pdf:	fourier.tex
	pdflatex fourier.tex

pi2.pdf:	pi2.tex
	pdflatex pi2.tex

