#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-joukowski =						\
	papers/joukowski/packages.tex					\
	papers/joukowski/main.tex					\
	papers/joukowski/chapters/1_einleitung.tex			\
	papers/joukowski/chapters/2_voraussetzungen.tex			\
	papers/joukowski/chapters/3_auftriebskraft.tex			\
	papers/joukowski/chapters/4_komplexe_analysis.tex		\
	papers/joukowski/chapters/5_stroemungslinien.tex		\
	papers/joukowski/chapters/6_beispiel.tex			\
	papers/joukowski/references.bib	
