#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-laplace =						\
	papers/laplace/packages.tex					\
	papers/laplace/main.tex					\
	papers/laplace/references.bib				\
	papers/laplace/01_einleitung.tex					\
	papers/laplace/01_herleitung.tex					\
	papers/laplace/02_residuensatz.tex					\
	papers/laplace/03_verzweigung.tex					\
	papers/laplace/04_endlicher_stab.tex					\
	papers/laplace/05_talbot.tex
