%
% li.m --
%
% (c) 2026 Prof Dr Andreas Müller
%
N = 100

function retval = f(x, t)
	retval = 1 / log(t);
end

function kurve(fn, name, t, x)
	n = size(t)(2);
	fprintf(fn, "\\def\\kurve%s{", name);
	fprintf(fn, "\n\t(%.4f,%.4f)", t(1), x(1));
	for i = (2:n)
		fprintf(fn, "\n\t-- (%.4f,%.4f)", t(i), x(i));
	end
	fprintf(fn, "\n}\n");
end

fn = fopen("lipaths.tex", "w");

fprintf(fn, "%%\n");
fprintf(fn, "%% lipaths.tex -- generated by li.m, don't edit\n");
fprintf(fn, "%%\n");
fprintf(fn, "%% (c) 2026 Prof Dr Andreas Müller\n");
fprintf(fn, "%%\n");

t0 = 0.0000001;
t1 = 0.9999;
t = linspace(t0, t1, N)
x0 = 0;
x = lsode(@f, x0, t);

kurve(fn, "null", t, x);

t0 = 2;
t1 = 1.001;
t = linspace(t0, t1, N);
x0 = 1.0451637801;
x = lsode(@f, x0, t);

kurve(fn, "zweilinks", t, x);

t1 = 10;
t = linspace(t0, t1, N);
x = lsode(@f, x0, t);

kurve(fn, "zweirechts", t, x);

fclose(fn);

