%
% li2.m -- dilogarithm graph
%
% (c) 2026 Prof Dr Andreas Müller
%
N = 100

function retval = f(x, t)
	retval = -log(1-t)/t;
end

function kurve(fn, name, t, x)
	n = size(t)(2);
	fprintf(fn, "\\def\\kurve%s{", name);
	fprintf(fn, "\n\t(%.4f,%.4f)", t(1), x(1));
	for i = (2:n)
		fprintf(fn, "\n\t-- (%.4f,%.4f)", t(i), x(i));
	end
	fprintf(fn, "\n}\n");
end

fn = fopen("li2paths.tex", "w");

fprintf(fn, "%%\n");
fprintf(fn, "%% lipaths.tex -- generated by li.m, don't edit\n");
fprintf(fn, "%%\n");
fprintf(fn, "%% (c) 2026 Prof Dr Andreas Müller\n");
fprintf(fn, "%%\n");

t0 = 0.0000001;
t1 = 0.9999;
t = linspace(t0, t1, N)
x0 = 0;
x = lsode(@f, x0, t);

kurve(fn, "links", t, x);

t0 = -0.00001;
t1 = -5;
t = linspace(t0, t1, N);
x0 = 0;
x = lsode(@f, x0, t);

kurve(fn, "rechts", t, x);

fclose(fn);

