#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-resultante =						\
	papers/resultante/packages.tex					\
	papers/resultante/main.tex					\
	papers/resultante/references.bib				\
	papers/resultante/teil0.tex					\
	papers/resultante/teil1.tex					\
	papers/resultante/teil2.tex					\
	papers/resultante/teil3.tex

