#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-gamma =							\
	papers/gamma/packages.tex					\
	papers/gamma/main.tex						\
	papers/gamma/references.bib					\
	papers/gamma/fakultaet.tex					\
	papers/gamma/spheres.tex					\
	papers/gamma/spheres_drawings.tex				\
	papers/gamma/spheres_with_gamma.tex
