#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
AUFGABENFILES +=							\
	chapters/070-intalg/uebungsaufgaben/701.tex			\
	chapters/070-intalg/uebungsaufgaben/702.tex			\
	chapters/070-intalg/uebungsaufgaben/703.tex			\
	chapters/070-intalg/uebungsaufgaben/704.tex			\
	chapters/070-intalg/uebungsaufgaben/705.tex			\
	chapters/070-intalg/uebungsaufgaben/706.tex			\
	chapters/070-intalg/uebungsaufgaben/707.tex

CHAPTERFILES += 							\
	chapters/070-intalg/1-elementar.tex				\
	chapters/070-intalg/11-funktionenkoerper.tex			\
	chapters/070-intalg/12-differential.tex				\
	chapters/070-intalg/13-explog.tex				\
	chapters/070-intalg/14-trigo.tex				\
	chapters/070-intalg/15-elementar.tex				\
	chapters/070-intalg/16-ableitung.tex				\
	chapters/070-intalg/2-wurzel.tex				\
	chapters/070-intalg/21-koerper.tex				\
	chapters/070-intalg/22-rational.tex				\
	chapters/070-intalg/23-integration.tex				\
	chapters/070-intalg/24-polynom.tex				\
	chapters/070-intalg/25-partial.tex				\
	chapters/070-intalg/26-1theta.tex				\
	chapters/070-intalg/27-pol.tex					\
	chapters/070-intalg/28-erfahrung.tex				\
	chapters/070-intalg/3-liouville.tex				\
	chapters/070-intalg/31-prinzip.tex				\
	chapters/070-intalg/32-polynome.tex				\
	chapters/070-intalg/33-spezial.tex				\
	chapters/070-intalg/34-allgemein.tex				\
	chapters/070-intalg/4-risch.tex					\
	chapters/070-intalg/41-uebersicht.tex				\
	chapters/070-intalg/42-log.tex					\
	chapters/070-intalg/43-exp.tex					\
	chapters/070-intalg/44-alg.tex					\
	chapters/070-intalg/fig/fig-invcis.tex				\
	chapters/070-intalg/fig/fig-invtan.tex				\
	chapters/070-intalg/fig/lf.tex					\
	chapters/070-intalg/fig/polylog.tex				\
	chapters/070-intalg/fig/fig-li.tex				\
	chapters/070-intalg/fig/fig-li2.tex				\
	chapters/070-intalg/fig/fig-ei.tex				\
	chapters/070-intalg/chapter.tex

