#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
AUFGABENFILES +=							\
	chapters/010-komplex/uebungsaufgaben/101.tex			\
	chapters/010-komplex/uebungsaufgaben/102.tex

CHAPTERFILES += 							\
	chapters/010-komplex/1-zahlen.tex				\
	chapters/010-komplex/11-reell.tex				\
	chapters/010-komplex/12-algebraisch.tex				\
	chapters/010-komplex/13-komplex.tex				\
	chapters/010-komplex/14-matrix.tex				\
	chapters/010-komplex/15-geometrisch.tex				\
	chapters/010-komplex/16-quaternionen.tex			\
	chapters/010-komplex/2-funktionen.tex				\
	chapters/010-komplex/21-abbildungen.tex				\
	chapters/010-komplex/22-polynome.tex				\
	chapters/010-komplex/23-potenzreihen.tex			\
	chapters/010-komplex/3-fundamental.tex				\
	chapters/010-komplex/31-nullstellenc.tex			\
	chapters/010-komplex/32-nullstellenq.tex			\
	chapters/010-komplex/4-symmetrisch.tex				\
	chapters/010-komplex/41-elementar.tex				\
	chapters/010-komplex/42-matrix.tex				\
	chapters/010-komplex/fig/table-gold.tex				\
	chapters/010-komplex/fig/fig-farben.tex				\
	chapters/010-komplex/fig/fig-fundamental.tex			\
	chapters/010-komplex/fig/fig-gaussebene.tex			\
	chapters/010-komplex/fig/fig-gausszahlen.tex			\
	chapters/010-komplex/fig/fig-hamilton.tex			\
	chapters/010-komplex/fig/fig-hyperbeln.tex			\
	chapters/010-komplex/fig/fig-kehrwert.tex			\
	chapters/010-komplex/fig/table-gold.tex				\
	chapters/010-komplex/chapter.tex

