%
% zerocurves.m
%
% (c) 2026 Prof Dr Andreas Müller
%
global polynom;
polynom = [ 1, 0, 3, 1, 5, 1 + 1i ];
global degree;
degree = 5;

function retval = points(v)
	global polynom;
	n = size(polynom)(2);
	d = zeros(1,n);
	d(1,n) = v;
	retval = roots(polynom + d);
end

function	retval = sortbyclosest(new, old)
	global	degree;
	retval = zeros(degree,1);
	for i = (1:degree)
		d = 10000;
		for k = (1:degree)
			abstand = norm(new(k,1) - old(i,1));
			if (abstand < d)
				retval(i,1) = new(k,1);
				d = abstand;
			end
		end
	end
	retval
end

function	retval = curves(direction)
	global degree;
	deltat = 0.01;
	t = -10;

	start = points(t^degree * direction);

	counter = 1;
	retval = start;

	while (t < 10)
		t = t + deltat;
		counter = counter + 1;
		new = points(t^degree * direction)
		retval(:,counter) = sortbyclosest(new, retval(:,counter-1));
	end
end

function	writecurve(fn, name, data, color, index)
	n = size(data)(2);
	fprintf(fn, "\\def\\%s{\n", name);
	fprintf(fn, "\t\\draw[color=%s,line width=1.2pt]", color);
	delimiter = "";
	for i = (1:n)
		p = data(index, i);
		fprintf(fn, "\n\t%s({%.4f*\\dx},{%.4f*\\dy})", delimiter,
			real(p), imag(p));
		delimiter = "-- ";
	end
	fprintf(fn, ";\n");
	fprintf(fn, "}\n");
end

function	writecurves(fn, name, data, color)
	n = size(data)(1);
	for i = (1:n)
		fullname = sprintf("%s%c", name, char(64 + i));
		writecurve(fn, fullname, data, color, i);
	end
end

realcurves = curves(1);
imagcurves = curves(1i);

fn = fopen("zerocurves.tex", "w");

fprintf(fn, "%%\n");
fprintf(fn, "%% zerocurves.tex -- generated by zerocurves.m, do not edit \n");
fprintf(fn, "%%\n");
fprintf(fn, "%% (c) 2026 Prof Dr Andreas Müller \n");
fprintf(fn, "%%\n");

writecurves(fn, "real", realcurves, "darkred");
writecurves(fn, "imag", imagcurves, "blue");

p = points(0);
for i = (1:degree)
	z = p(i,1);
	fprintf(fn, "\\def\\zero%c{\n", char(64 + i));
	fprintf(fn, "\\fill[color=black] ({%.4f*\\dx},{%.4f*\\dy}) circle[radius=0.08];\n", real(z), imag(z));
	w = z + 0.30 * z/abs(z);
	fprintf(fn, "\\zerolabel{%.4f}{%.4f}{z_%d}\n", real(w), imag(w), i);
	fprintf(fn, "}\n");
end

fclose(fn);
