#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter0 =								\
	../slides/0/info.tex						\
	../slides/0/was.tex						\
	../slides/0/frueher.tex						\
	../slides/0/themen.tex						\
	../slides/0/latextipps.tex					\
	../slides/0/nextsteps.tex					\
	../slides/0/vortraege.tex					\
	../slides/0/semesterplan.tex					\
	../slides/0/aufgaben.tex					\
	../slides/0/inhalt.tex
