#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
AUFGABENFILES +=							\
	chapters/060-ratint/uebungsaufgaben/601.tex			\
	chapters/060-ratint/uebungsaufgaben/602.tex			\
	chapters/060-ratint/uebungsaufgaben/603.tex			\
	chapters/060-ratint/uebungsaufgaben/604.tex

CHAPTERFILES += 							\
	chapters/060-ratint/1-bernoulli.tex				\
	chapters/060-ratint/11-problem.tex				\
	chapters/060-ratint/12-partial.tex				\
	chapters/060-ratint/13-reell.tex				\
	chapters/060-ratint/14-prinzip.tex				\
	chapters/060-ratint/2-euklid.tex				\
	chapters/060-ratint/21-euklidganz.tex				\
	chapters/060-ratint/22-polynome.tex				\
	chapters/060-ratint/23-euklidisch.tex				\
	chapters/060-ratint/24-koerper.tex				\
	chapters/060-ratint/3-hermite.tex				\
	chapters/060-ratint/31-quadratfrei.tex				\
	chapters/060-ratint/32-reduktion.tex				\
	chapters/060-ratint/4-rothsteintrager.tex			\
	chapters/060-ratint/41-residuen.tex				\
	chapters/060-ratint/42-rt.tex					\
	chapters/060-ratint/fig/fig-ggz.tex				\
	chapters/060-ratint/fig/tabular-euklid.tex			\
	chapters/060-ratint/chapter.tex

