#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

AUFGABENFILES +=							\
	chapters/030-integration/uebungsaufgaben/301.tex		\
	chapters/030-integration/uebungsaufgaben/302.tex		\
	chapters/030-integration/uebungsaufgaben/303.tex		\
	chapters/030-integration/uebungsaufgaben/304.tex

CHAPTERFILES += 							\
	chapters/030-integration/1-wegintegral.tex			\
	chapters/030-integration/11-wege.tex				\
	chapters/030-integration/12-integral.tex			\
	chapters/030-integration/13-homotopie.tex			\
	chapters/030-integration/2-cauchy.tex				\
	chapters/030-integration/21-geschlossen.tex			\
	chapters/030-integration/22-harmonisch.tex			\
	chapters/030-integration/23-ableitungen.tex			\
	chapters/030-integration/24-liouville.tex			\
	chapters/030-integration/3-umlaufzahl.tex			\
	chapters/030-integration/31-definition.tex			\
	chapters/030-integration/32-integration.tex			\
	chapters/030-integration/33-integralsatz.tex			\
	chapters/030-integration/34-ableitungen.tex			\
	chapters/030-integration/4-residuen.tex				\
	chapters/030-integration/41-beispiel.tex			\
	chapters/030-integration/42-methode.tex				\
	chapters/030-integration/43-pole.tex				\
	chapters/030-integration/44-hauptwert.tex			\
	chapters/030-integration/5-homologie.tex			\
	chapters/030-integration/51-kettenzyklen.tex			\
	chapters/030-integration/52-kettenintegral.tex			\
	chapters/030-integration/53-homologie.tex			\
	chapters/030-integration/54-hgruppe.tex				\
	chapters/030-integration/55-dimension.tex			\
	chapters/030-integration/fig/fig-argument.tex			\
	chapters/030-integration/fig/fig-beliebig.tex			\
	chapters/030-integration/fig/fig-cauchyverteilung.tex		\
	chapters/030-integration/fig/fig-deformation.tex		\
	chapters/030-integration/fig/fig-dreiecke.tex			\
	chapters/030-integration/fig/fig-ecos.tex			\
	chapters/030-integration/fig/fig-green.tex			\
	chapters/030-integration/fig/fig-hauptwert.tex			\
	chapters/030-integration/fig/fig-homotopie.tex			\
	chapters/030-integration/fig/fig-kettenzyklen.tex		\
	chapters/030-integration/fig/fig-lochgebiet.tex			\
	chapters/030-integration/fig/fig-merohomolog.tex		\
	chapters/030-integration/fig/fig-methode.tex			\
	chapters/030-integration/fig/fig-paar.tex			\
	chapters/030-integration/fig/fig-raender.tex			\
	chapters/030-integration/fig/fig-rechteck.tex			\
	chapters/030-integration/fig/fig-residuum.tex			\
	chapters/030-integration/fig/fig-sinxx.tex			\
	chapters/030-integration/fig/fig-wege.tex			\
	chapters/030-integration/chapter.tex

