#
# Makefile -- build images
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	dreieck-konstruktion.pdf					\
	napoleon.pdf							\
	pdn-quadrat.pdf

dreieck-konstruktion.pdf: dreieck-konstruktion.tex
	pdflatex dreieck-konstruktion.tex

napoleon.pdf: napoleon.tex
	pdflatex napoleon.tex

pdn-quadrat.pdf: pdn-quadrat.tex
	pdflatex pdn-quadrat.tex

