%
% konform.m
%
% (c) 2026 Prof Dr Andreas Müller
%
global Dx;
Dx = 0.2;
global Dy;
Dy = 0.2;

global xmin;
global xmax;
global ymin;
global ymax;

xmin = 0.5;
xmax = 2.5;
ymin = 0.5;
ymax = 2.5;

global tmin;
global tmax;
global dt;
tmin = 0;
tmax = 2;
dt = 0.01;

function retval = f(x)
	retval = sin(x) + x^2;
end

function retval = fprime(x)
	retval = cos(x) + 2 * x;
end

function retval = curve(start, direction)
	global tmax;
	global dt;
	epsilon = 0.00000001;
	t = 0;
	i = 1;
	retval = zeros(1,1);
	tmax
	dt
	while (t < (tmax + epsilon))
		z = start + direction * t
		retval(i) = f(z);
		i = i + 1;
		t = t + dt;
	end
	retval
end

function drawcurve(fn, name, data, idx)
	n = size(data)(2);
	fprintf(fn, "%% name = %s, curve = %d\n", name, idx);
	idx
	fprintf(fn, "\\def\\%s{", name);
	delimiter = "";
	for i = (1:n)
		z = data(idx, i);
		fprintf(fn, "\n\t%s({%.4f*\\dx},{%.4f*\\dy})", delimiter,
			real(z), imag(z));
		if (i == 1)
			delimiter = "-- ";
		end
	end
	fprintf(fn, "\n}\n");
end

function drawcurves(fn, name, data)
	d = size(data)(1);
	for i = (1:d)
		fullname = sprintf("%s%c", name, char(64 + i));
		drawcurve(fn, fullname, data, i);
	end
end

function retval = computecurves(curvedirection, from, to, step)
	data = zeros(1,1);
	global xmin;
	global ymin;
	if (curvedirection == 1)
		zmin = xmin;
		otherdirection = 1i;
	else
		zmin = ymin;
		otherdirection = 1;
	end
	k = 1;
	for z = (from:step:to)
		z0 = zmin * curvedirection + otherdirection * z
		p = curve(z0, curvedirection);
		if (size(data)(2) == 1)
			data = zeros(1,size(p)(2));
		end
		data(k,:) = p;
		k = k + 1;
	end
	retval = data;
end

fn = fopen("konformcurves.tex", "w");

fprintf(fn, "%%\n");
fprintf(fn, "%% konformcurves.tes -- generated by konform.m, don't edit \n");
fprintf(fn, "%%\n");
fprintf(fn, "%% (c) 2026 Prof Dr Andreas Müller\n");
fprintf(fn, "%%\n");

data = computecurves(1, ymin, ymax, Dy);
drawcurves(fn, "real", data);

data = computecurves(1i, xmin, xmax, Dy);
drawcurves(fn, "imag", data);

z = 1.1 + 1.1i;
w = f(z);
w1 = 0.4;
w2 = 0.9;
r = 1.8;

tmax = 1.4;
d = exp(1i * w1 * pi/2)
curve1 = curve(z, d);

fprintf(fn, "\\def\\kurvea{\n");
p = curve1(1,1);
fprintf(fn, "\t({%.4f*\\dx},{%.4f*\\dy})", real(p), imag(p));
n = size(curve1)(2)
for i = (2:n)
	p = curve1(1,i);
	fprintf(fn, "\n\t-- ({%.4f*\\dx},{%.4f*\\dy})", real(p), imag(p));
end
fprintf(fn, "\n}\n");

d = exp(1i * w2 * pi/2)
curve2 = curve(z, d);
fprintf(fn, "\\def\\kurveb{\n");
p = curve2(1,1);
fprintf(fn, "\t({%.4f*\\dx},{%.4f*\\dy})", real(p), imag(p));
n = size(curve2)(2)
for i = (2:n)
	p = curve2(1,i);
	fprintf(fn, "\n\t-- ({%.4f*\\dx},{%.4f*\\dy})", real(p), imag(p));
end
fprintf(fn, "\n}\n");

fprintf(fn, "\\def\\winkel{\n");
	fprintf(fn, "\\node at ({%.4f*\\dx},{%.4f*\\dy}) ", real(w), imag(w));
	fprintf(fn, "[below] {$f(z_0)$};\n");

	zd = exp(1i * w2 * pi / 2);
	wd = fprime(z) * zd;
	wd = 2 * wd / abs(wd);
	wd2 = arg(wd);
	fprintf(fn, "\\draw[color=darkgreen] ({%.4f*\\dx},{%.4f*\\dy})",
		real(w), imag(w));
	fprintf(fn, " -- ++({%.4f*\\dx},{%.4f*\\dy});\n", real(wd), imag(wd));

	zd = exp(1i * w1 * pi / 2);
	wd = fprime(z) * zd;
	wd = 2 * wd / abs(wd);
	wd1 = arg(wd);
	fprintf(fn, "\\draw[color=darkgreen] ({%.04f*\\dx},{%.04f*\\dy})",
		real(w), imag(w));
	fprintf(fn, " -- ++({%.4f*\\dx},{%.4f*\\dy});\n", real(wd), imag(wd));


	fprintf(fn, "\\fill[color=darkgreen] ({%.4f*\\dx},{%.4f*\\dy}) ",
		real(w), imag(w));
	fprintf(fn, " circle[radius=0.08];\n");

	zd = exp(1i * ((w1 + wd)/2) * pi / 2);
	wd = fprime(z) * zd;
	wd = 2 * wd / abs(wd);
	fprintf(fn, "\\node[color=darkgreen] at ");
	fprintf(fn, "($({%.4f*\\dx},{%.4f*\\dy})+(%.2f:1.3)$) ",
		real(w), imag(w), 180*(wd1 + wd2)/(2*pi));
	fprintf(fn, "\t{$\\omega$};\n");

fprintf(fn, "}\n");

fprintf(fn, "\\def\\fwinkel{\n");
	fprintf(fn, "\\fill[color=darkgreen!40,opacity=0.5] ");
	fprintf(fn, "({%.4f*\\dx},{%.4f*\\dy}) ", real(w), imag(w));
	fprintf(fn, "\n\t-- ++(%.3f:%.4f) arc (%.3f:%.3f:%.4f) -- cycle;\n",
		180 * wd1 / pi, r, 180 * wd1 / pi, 180 * wd2 / pi, r);
fprintf(fn, "}\n");

fclose(fn);
